// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0pqCXy5zdMaV3LBCKv3D2ea6_jVhbOxU',
    appId: '1:711357475497:web:8fe3a8b24e7fb16e5c97b8',
    messagingSenderId: '711357475497',
    projectId: 'ex-din',
    authDomain: 'ex-din.firebaseapp.com',
    storageBucket: 'ex-din.appspot.com',
    measurementId: 'G-E1XD913X4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD58dUj2m-RbMAa4xbRYOnHScE5KlUCDHo',
    appId: '1:711357475497:android:c8f9d89950a5d9e05c97b8',
    messagingSenderId: '711357475497',
    projectId: 'ex-din',
    storageBucket: 'ex-din.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ShLzX-p5rAsD4kgZzSeB11pLrF5pB2o',
    appId: '1:711357475497:ios:d6533222fbdc56f95c97b8',
    messagingSenderId: '711357475497',
    projectId: 'ex-din',
    storageBucket: 'ex-din.appspot.com',
    iosClientId: '711357475497-5ppt7et3btq07ivdu10nh9st7c5nloqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.exDin',
  );
}
